# Generated by Django 3.2.5 on 2021-07-13 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_year', models.DateField(verbose_name='Month')),
                ('cost', models.DecimalField(decimal_places=4, max_digits=8, verbose_name='Cost')),
            ],
        ),
    ]
