# Generated by Django 3.2.5 on 2021-07-19 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataapi', '0002_auto_20210715_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energycost',
            name='cost',
            field=models.FloatField(verbose_name='Cost'),
        ),
        migrations.AlterField(
            model_name='energycost',
            name='month_year',
            field=models.DateField(unique=True, verbose_name='Month'),
        ),
    ]
