# Generated by Django 3.2.5 on 2021-07-19 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataapi', '0003_auto_20210719_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energycost',
            name='month_year',
            field=models.DateField(verbose_name='Month'),
        ),
        migrations.AlterUniqueTogether(
            name='energycost',
            unique_together={('month_year', 'trading_company')},
        ),
    ]
